STAT_CATEGORY_LOOKUP = {
    "passingAttempts": "Passing",
    "passingCompletions": "Passing",
    "passingIncompletions": "Passing",
    "passingYards": "Passing",
    "passingTouchdowns": "Passing",
    "passing40PlusYardTD": "Passing",
    "passing50PlusYardTD": "Passing",
    "passing300To399YardGame": "Passing",
    "passing400PlusYardGame": "Passing",
    "passing2PtConversions": "Passing",
    "passingInterceptions": "Passing",
    "passingCompletionPercentage": "Passing",
    "passingTimesSacked": "Passing",
    "rushingAttempts": "Rushing",
    "rushingYards": "Rushing",
    "rushingTouchdowns": "Rushing",
    "rushing2PtConversions": "Rushing",
    "rushing40PlusYardTD": "Rushing",
    "rushing50PlusYardTD": "Rushing",
    "rushing100To199YardGame": "Rushing",
    "rushing200PlusYardGame": "Rushing",
    "rushingYardsPerAttempt": "Rushing",
    "receivingReceptions": "Receiving",
    "receivingYards": "Receiving",
    "receivingTouchdowns": "Receiving",
    "receiving2PtConversions": "Receiving",
    "receiving40PlusYardTD": "Receiving",
    "receiving50PlusYardTD": "Receiving",
    "receiving100To199YardGame": "Receiving",
    "receiving200PlusYardGame": "Receiving",
    "receivingTargets": "Receiving",
    "receivingYardsAfterCatch": "Receiving",
    "receivingYardsPerReception": "Receiving",
    "madeFieldGoalsFrom50Plus": "Kicking",
    "attemptedFieldGoalsFrom50Plus": "Kicking",
    "missedFieldGoalsFrom50Plus": "Kicking",
    "madeFieldGoalsFrom40To49": "Kicking",
    "attemptedFieldGoalsFrom40To49": "Kicking",
    "missedFieldGoalsFrom40To49": "Kicking",
    "madeFieldGoalsFromUnder40": "Kicking",
    "attemptedFieldGoalsFromUnder40": "Kicking",
    "missedFieldGoalsFromUnder40": "Kicking",
    "madeFieldGoals": "Kicking",
    "attemptedFieldGoals": "Kicking",
    "missedFieldGoals": "Kicking",
    "madeExtraPoints": "Kicking",
    "attemptedExtraPoints": "Kicking",
    "missedExtraPoints": "Kicking",
    "madeFieldGoalsFrom60Plus": "Kicking",
    "attemptedFieldGoalsFrom60Plus": "Kicking",
    "missedFieldGoalsFrom60Plus": "Kicking",
    "madeFieldGoalsFrom50To59": "Kicking",
    "attemptedFieldGoalsFrom50To59": "Kicking",
    "missedFieldGoalsFrom50To59": "Kicking",
    "netPunts": "Punting",
    "puntYards": "Punting",
    "puntsInsideThe10": "Punting",
    "puntsInsideThe20": "Punting",
    "blockedPunts": "Punting",
    "puntTouchbacks": "Punting",
    "puntFairCatches": "Punting",
    "puntAverage": "Punting",
    "puntAverage44.0+": "Punting",
    "puntAverage42.0-43.9": "Punting",
    "puntAverage40.0-41.9": "Punting",
    "puntAverage38.0-39.9": "Punting",
    "puntAverage36.0-37.9": "Punting",
    "puntAverage34.0-35.9": "Punting",
    "puntAverage33.9AndUnder": "Punting",
    "defensive0PointsAllowed": "Defensive",
    "defensive1To6PointsAllowed": "Defensive",
    "defensive7To13PointsAllowed": "Defensive",
    "defensive14To17PointsAllowed": "Defensive",
    "defensiveBlockedKickForTouchdowns": "Defensive",
    "defensiveTouchdowns": "Defensive",
    "defensiveInterceptions": "Defensive",
    "defensiveFumbles": "Defensive",
    "defensiveBlockedKicks": "Defensive",
    "defensiveSafeties": "Defensive",
    "defensiveSacks": "Defensive",
    "defensivePlusSpecialTeamsTouchdowns": "Defensive",
    "defensiveForcedFumbles": "Defensive",
    "defensiveAssistedTackles": "Defensive",
    "defensiveSoloTackles": "Defensive",
    "defensiveTotalTackles": "Defensive",
    "defensivePassesDefensed": "Defensive",
    "defensivePointsAllowed": "Defensive",
    "defensive18To21PointsAllowed": "Defensive",
    "defensive22To27PointsAllowed": "Defensive",
    "defensive28To34PointsAllowed": "Defensive",
    "defensive35To45PointsAllowed": "Defensive",
    "defensive45PlusPointsAllowed": "Defensive",
    "defensiveYardsAllowed": "Defensive",
    "defensiveLessThan100YardsAllowed": "Defensive",
    "defensive100To199YardsAllowed": "Defensive",
    "defensive200To299YardsAllowed": "Defensive",
    "defensive300To349YardsAllowed": "Defensive",
    "defensive350To399YardsAllowed": "Defensive",
    "defensive400To449YardsAllowed": "Defensive",
    "defensive450To499YardsAllowed": "Defensive",
    "defensive500To549YardsAllowed": "Defensive",
    "defensive550PlusYardsAllowed": "Defensive",
    "defensive2PtReturns": "Defensive",
    "kickoffReturnYardsEvery10": "Return",
    "kickoffReturnYardsEvery25": "Return",
    "kickoffReturnTouchdowns": "Return",
    "puntReturnTouchdowns": "Return",
    "kickoffReturnYards": "Return",
    "puntReturnYards": "Return",
    "puntsReturned": "Return",
    "fumbleRecoveredForTD": "Turnovers",
    "fumbles": "Turnovers",
    "lostFumbles": "Turnovers",
    "turnovers": "Turnovers",
    "interceptionReturnTouchdowns": "Turnovers",
    "fumbleReturnTouchdowns": "Turnovers",
    "teamWin": "Team/Head Coach",
    "teamLoss": "Team/Head Coach",
    "teamTie": "Team/Head Coach",
    "pointsScored": "Team/Head Coach",
    "pointsMargin": "Team/Head Coach",
    "25+pointWinMargin": "Team/Head Coach",
    "20-24pointWinMargin": "Team/Head Coach",
    "15-19pointWinMargin": "Team/Head Coach",
    "10-14pointWinMargin": "Team/Head Coach",
    "5-9pointWinMargin": "Team/Head Coach",
    "1-4pointWinMargin": "Team/Head Coach",
    "1-4pointLossMargin": "Team/Head Coach",
    "5-9pointLossMargin": "Team/Head Coach",
    "10-14pointLossMargin": "Team/Head Coach",
    "15-19pointLossMargin": "Team/Head Coach",
    "20-24pointLossMargin": "Team/Head Coach",
    "25+pointLossMargin": "Team/Head Coach",
    "winPercentage": "Team/Head Coach",
    "2PtConversions": "Miscellaneous",
}
